# Basic dependabot.yml file with

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: 'npm'
    # Look for `package.json` and `lock` files in the `root` directory
    directory: '/'
    # Check the npm registry for updates every day (weekdays)
    schedule:
      interval: 'weekly'
    versioning-strategy: increase
    groups:
      babel:
        patterns:
          - '@babel/core'
          - '@babel/runtime'
          - '@babel/runtime-corejs3'
          - '@babel/preset-*'
      babel-plugins:
        patterns:
          - '@babel/plugin-*'
          - 'babel-plugin-*'
          - 'react-refresh'
